Fix error C2338: static_assert failed: 'N4971 [rand.util.seedseq]/7 requires the value type of the iterator to be an unsigned type that is at least 32-bit.'